;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-item
	cdlatex-pbb
	corfu-next
	electric-pair-delete-pair
	evil-append
	evil-backward-char
	evil-change
	evil-delete-char
	evil-force-normal-state
	evil-forward-char
	evil-forward-word-begin
	evil-insert
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-scroll-up
	evil-substitute
	evil-undo
	evil-yank
	keyboard-escape-quit
	keyboard-quit
	mc/mark-next-lines
	org-delete-char
	org-self-insert-command
	paredit-open-round
	paredit-raise-sexp
	))

(setq mc/cmds-to-run-once
      '(
	evil-exit-visual-state
	evil-mouse-drag-region
	))
