;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-item
        cdlatex-pbb
        evil-backward-char
        evil-change
        evil-forward-char
        evil-insert
        evil-normal-state
        keyboard-escape-quit
        keyboard-quit
        mc/mark-next-lines
        org-delete-char
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
