
font_family      Iosevka Nerd Font
# font_family      JetBrains Mono Nerd Font
# font_family      MesloLGS Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 15.0
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

dynamic_background_opacity yes

# Отправка SIGINT (Ctrl+C) при нажатии Ctrl+Alt+C
map ctrl+alt+c send_text all \x03

# Отправка EOF (Ctrl+D) при нажатии Ctrl+Alt+D
map ctrl+alt+d send_text all \x04

# Отправка SIGTSTP (Ctrl+Z) при нажатии Ctrl+Alt+Z
map ctrl+alt+z send_text all \x1A

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME

# background #22334a
